---

# Используем скрипт на python и проверку assert в ansible
- name: Test with script and assert
  script: test_file_exists.py "{{ input_excel_uri }}"
  register: cmd_result
  
- assert:
    that:
      - "'File does not exist' not in cmd_result.stderr"
      - "'File exists' in cmd_result.stdout"
  register: pytest_assert_result
  ignore_errors: yes

- name: Debug output of test 1
  debug:
      msg: "{{ cmd_result }}"
    
- name: Debug output of assert 1
  debug:
      msg: "{{ pytest_assert_result }}"

# Проверка только с использованием модулей ansible
- name: Test with stat and assert
  stat: 
    path: "{{ input_excel_uri }}" 
  register: file_check_result
  tags: input_test

- assert:
    that:
      - file_check_result.stat.exists
  register: assert_result
  ignore_errors: yes
 
# Too mush info 
#- name: Debug output of test 2
#  debug:
#      msg: "{{ file_check_result }}"

- name: Fail if something went wrong (debug output of assert 2)
  fail: 
      msg: "{{ assert_result }} File path: {{ input_excel_uri }}"
  when: assert_result.failed
  
- name: Debug output of assert 2
  debug:
      msg: "{{ assert_result }} File path: {{ input_excel_uri }}"