---
# Playbook is used to fill csv table with data about network connections
- name: Fill csv file with data
  connection: local
  gather_facts: yes
  hosts: localhost
  tasks: 
    - import_role: 
        name: fill_csv
      tags: csv